interface poke {
    variant request {
        send(send-request),
    }

    variant response {
        send,
    }

    record send-request {
        target: string,
    }
}

world poke-tantum-ergo-dot-os-v0 {
    import poke;
    import notify;
    include process-v0;
}
